server:
  port: 8080
spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
  main:
    allow-circular-references: true

jwt:
  security:
    secret: antonio123
cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}
