spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasklist
      username: postgres
      password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update