spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: tasklist
      port: 27017
      host: localhost
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update