spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: tasklist
      port: 27017
      host: localhost
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: create-drop