spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: rootuser
#      password: rootpass
#      database: tasklist
#      port: 27017
#      host: localhost
#      auto-index-creation: true
      uri: mongodb+srv://admin:admin@lucaslucenak.vm9cmaj.mongodb.net/?retryWrites=true&w=majority
      database: tasklist
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  graphql:
    graphiql:
      enable: true